name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: Test reports
          path: build/reports/tests/test
  lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Super-Linter
          uses: github/super-linter@v4.10.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VALIDATE_ALL_CODEBASE: false
            DEFAULT_BRANCH: main
